Règlement (CE) no 553/2005 de la Commission
prévoyant une nouvelle attribution de droits d'importation au titre du règlement (CE) no 1081/1999 pour les taureaux, vaches et génisses, autres que ceux destinés à la boucherie, de certaines races alpines et de montagne
LA COMMISSION DES COMMUNAUTÉS EUROPÉENNES,
vu le traité instituant la Communauté européenne,
vu le règlement (CE) no 1254/1999 du Conseil du 17 mai 1999 portant organisation commune des marchés dans le secteur de la viande bovine [1],
vu le règlement (CE) no 1081/1999 de la Commission du 26 mai 1999 portant ouverture et mode de gestion de contingents tarifaires d'importation pour des taureaux, vaches et génisses, autres que ceux destinés à la boucherie, de certaines races alpines et de montagne, abrogeant le règlement (CE) no 1012/98 et modifiant le règlement (CE) no 1143/98 [2], et notamment son article 9, paragraphe 3,
Les quantités visées à l'article 9, paragraphe 1, du règlement (CE) no 1081/1999 s'élèvent à:
- 3711 têtes pour le numéro d'ordre 09.0001,
- 3712 têtes pour le numéro d'ordre 09.0003.
Le présent règlement entre en vigueur le 12 avril 2005.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 554/2005 de la Commission
fixant les prix communautaires à la production et les prix communautaires à l'importation pour les œillets et les roses pour l'application du régime à l'importation de certains produits de la floriculture originaires de Jordanie
LA COMMISSION DES COMMUNAUTÉS EUROPÉENNES,
vu le traité instituant la Communauté européenne,
vu le règlement (CEE) no 4088/87 du Conseil du 21 décembre 1987 déterminant les conditions d'application des droits de douane préférentiels à l'importation de certains produits de la floriculture originaires de Chypre, d'Israël, de Jordanie et du Maroc ainsi que de Cisjordanie et de la bande de Gaza [1], et notamment son article 5, paragraphe 2, point a),
(1) L'article 2, paragraphe 2, et l'article 3 du règlement (CEE) no 4088/87 prévoient que des prix communautaires à l'importation et des prix communautaires à la production sont fixés tous les quinze jours pour les œillets uniflores (standard), les œillets multiflores (spray), les roses à grande fleur et les roses à petite fleur, et sont applicables pendant deux semaines. Conformément à l'article 1er ter du règlement (CEE) no 700/88 de la Commission du 17 mars 1988 portant certaines modalités d'application du régime applicable à l'importation dans la Communauté de certains produits de la floriculture originaires de Chypre, d'Israël, de Jordanie et du Maroc ainsi que de Cisjordanie et de la bande de Gaza [2], ces prix sont fixés pour des périodes de deux semaines sur la base des données pondérées fournies par les États membres.
(2) Il est important que lesdits prix soient fixés sans délai pour pouvoir déterminer les droits de douane à appliquer.
(3) À la suite de l’adhésion de Chypre à l’Union européenne au 1er mai 2004, il convient de ne plus fixer de prix à l'importation pour ce qui concerne ce pays.
(5) Dans l'intervalle des réunions du comité de gestion des plantes vivantes et des produits de la floriculture, la Commission doit prendre ces mesures,
Les prix communautaires à la production et les prix communautaires à l'importation pour les œillets uniflores (standard), les œillets multiflores (spray), les roses à grande fleur et les roses à petite fleur visés à l'article 1er du règlement (CEE) no 4088/87 sont fixés à l’annexe du présent règlement pour la période du 13 au 26 avril 2005.
Le présent règlement entre en vigueur le jour de sa publication au Journal officiel de l’Union européenne.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 555/2005 du Conseil
relatif à la conclusion du protocole fixant les possibilités de pêche thonière et la contrepartie financière prévues dans l'accord entre la Communauté économique européenne et la République démocratique de Madagascar concernant la pêche au large de Madagascar, pour la période allant du 1er janvier 2004 au 31 décembre 2006
LE CONSEIL DE L'UNION EUROPÉENNE,
vu le traité instituant la Communauté européenne, et notamment son article 37, en liaison avec l'article 300, paragraphe 2, et l'article 300, paragraphe 3, premier alinéa,
vu la proposition de la Commission,
vu l'avis du Parlement européen [1],
(1) Conformément à l'accord entre la Communauté économique européenne et la République démocratique de Madagascar concernant la pêche au large de Madagascar [2], les deux parties ont négocié pour déterminer les modifications ou compléments à introduire dans cet accord à la fin de la période d'application du protocole annexé à celui-ci.
(2) À la suite de ces négociations, un nouveau protocole fixant les possibilités de pêche et la contrepartie financière prévues dans l'accord précité pour la période du 1er janvier 2004 au 31 décembre 2006, a été paraphé le 8 septembre 2003.
(3) Il est dans l'intérêt de la Communauté d'approuver ledit protocole.
(4) Il importe de définir la clé de répartition des possibilités de pêche parmi les États membres en se basant sur la répartition des possibilités de pêche traditionnelle dans le cadre de l'accord de pêche,
Le protocole fixant les possibilités de pêche thonière et la contrepartie financière prévues dans l'accord entre la Communauté économique européenne et la République démocratique de Madagascar concernant la pêche au large de Madagascar, pour la période du 1er janvier 2004 au 31 décembre 2006, est approuvé au nom de la Communauté.
Le texte du protocole est joint au présent règlement.
Les possibilités de pêche fixées par le protocole sont réparties parmi les États membres selon la clé suivante:
Si les demandes de licence de ces États membres n'épuisent pas les possibilités de pêche fixées par le protocole, la Commission peut prendre en considération des demandes de licence de tout autre État membre.
Les États membres dont les navires pêchent dans le cadre du présent protocole sont tenus de notifier à la Commission les quantités de chaque stock capturées dans la zone de pêche malgache selon les modalités prévues par le règlement (CE) no 500/2001 de la Commission du 14 mars 2001 relatif à l'établissement des modalités d'application du règlement (CEE) no 2847/93 du Conseil relatif au contrôle des captures des navires de pêche communautaires dans les eaux des pays tiers et en haute mer [3].
Le président du Conseil est autorisé à désigner les personnes habilitées à signer le protocole à l'effet d'engager la Communauté.
Le présent règlement entre en vigueur le troisième jour suivant celui de sa publication au Journal officiel de l'Union européenne.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 556/2005 de la Commission
établissant les valeurs forfaitaires à l'importation pour la détermination du prix d'entrée de certains fruits et légumes
LA COMMISSION DES COMMUNAUTÉS EUROPÉENNES,
vu le traité instituant la Communauté européenne,
vu le règlement (CE) no 3223/94 de la Commission du 21 décembre 1994 portant modalités d'application du régime à l'importation des fruits et légumes [1], et notamment son article 4, paragraphe 1,
(1) Le règlement (CE) no 3223/94 prévoit, en application des résultats des négociations commerciales multilatérales du cycle d'Uruguay, les critères pour la fixation par la Commission des valeurs forfaitaires à l'importation des pays tiers, pour les produits et les périodes qu'il précise dans son annexe.
(2) En application des critères susvisés, les valeurs forfaitaires à l'importation doivent être fixées aux niveaux repris à l'annexe du présent règlement,
Les valeurs forfaitaires à l'importation visées à l'article 4 du règlement (CE) no 3223/94 sont fixées comme indiqué dans le tableau figurant en annexe.
Le présent règlement entre en vigueur le 13 avril 2005.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 557/2005 de la Commission
relatif à l'arrêt de la pêche de la crevette nordique par les navires battant pavillon d’un État membre à l’exception de l’Estonie, la Lettonie, la Lituanie et la Pologne
LA COMMISSION DES COMMUNAUTÉS EUROPÉENNES,
vu le traité instituant la Communauté européenne,
vu le règlement (CEE) no 2847/93 du Conseil du 12 octobre 1993 instituant un régime de contrôle applicable à la politique commune de la pêche [1], et notamment son article 21, paragraphe 3,
(1) Le règlement (CE) no 27/2005 du Conseil du 22 décembre 2004 établissant, pour 2005, les possibilités de pêche et les conditions associées pour certains stocks halieutiques et groupes de stocks halieutiques, applicables dans les eaux communautaires et, pour les navires communautaires, dans les eaux soumises à des limitations de capture, prévoit des quotas de crevette nordique pour 2005 [2].
(2) Afin d'assurer le respect des dispositions relatives aux limitations quantitatives des captures d'un stock soumis à quota, il est nécessaire que la Commission fixe la date à laquelle les captures effectuées par les navires battant pavillon d'un État membre sont réputées avoir épuisé le quota attribué.
(3) Selon les informations communiquées à la Commission, les captures de crevette nordique dans les eaux de la zone OPANO 3L effectuées par des navires battant pavillon d’un État membre ou enregistrés dans un État membre excepté l’Estonie, la Lettonie, la Lituanie et la Pologne ont atteint le quota attribué pour 2005. La Communauté a interdit la pêche de ce stock à partir du 24 février 2005. Il convient dès lors de retenir cette date,
Les captures de crevette nordique dans les eaux de la zone OPANO 3L effectuées par les navires battant pavillon d’un État membre ou enregistrés dans un État membre excepté l’Estonie, la Lettonie, la Lituanie et la Pologne sont réputées avoir épuisé le quota attribué à la Communauté pour 2005.
La pêche de la crevette nordique dans les eaux de la zone OPANO 3L effectuée par des navires battant pavillon d’un État membre ou enregistrés dans un État membre excepté l’Estonie, la Lettonie, la Lituanie et la Pologne est interdite, ainsi que la conservation à bord, le transbordement et le débarquement de ce stock capturé par ces navires après la date d'application de ce règlement.
Le présent règlement entre en vigueur le jour suivant celui de sa publication au Journal officiel de l'Union européenne.
Il est applicable à partir du 24 février 2005.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 558/2005 de la Commission
modifiant le règlement (CEE) no 3846/87 établissant la nomenclature des produits agricoles pour les restitutions à l'exportation et le règlement (CE) no 174/1999 établissant les modalités particulières d'application du règlement (CEE) no 804/68 du Conseil en ce qui concerne les certificats d'exportation et des restitutions à l'exportation dans le secteur du lait et des produits laitiers
LA COMMISSION DES COMMUNAUTÉS EUROPÉENNES,
vu le traité instituant la Communauté européenne,
vu le règlement (CE) no 1255/1999 du Conseil du 17 mai 1999 portant organisation commune des marchés dans le secteur du lait et des produits laitiers [1], et notamment son article 31, paragraphe 14,
(1) Le règlement (CEE) no 3846/87 de la Commission [2], sur la base de la nomenclature combinée, établit la nomenclature des produits agricoles pour les restitutions à l'exportation.
(2) La nomenclature des restitutions prévoit que les fromages sont éligibles à une restitution à l’exportation s’ils satisfont aux exigences minimales quant à la teneur en matière sèche du lait et en matière grasse du lait. Un type de fromage produit dans certains nouveaux États membres peut remplir ces exigences mais ne pas bénéficier d’une restitution car il n’est pas couvert par le système actuel de classification de la nomenclature des restitutions à l’exportation. Étant donné l’importance de ce fromage pour l’industrie laitière, le commerce et les producteurs laitiers impliqués, il convient d’ajouter un code de produit sous une position "autres fromages" afin que ce fromage puisse être classifié dans la nomenclature des restitutions à l’exportation.
(3) Les quantités pour lesquelles les certificats d'exportation sont nécessaires dans la catégorie de produits "fromages" dépassent constamment le niveau des limites d’exportation imposées à la Communauté en vertu de l’accord sur l’agriculture découlant des négociations commerciales multilatérales de l'Uruguay Round. Les certificats d’exportation supplémentaires qui seront demandés pour la position nouvellement créée augmenteront la pression sur cette catégorie.
(4) L’article 3 du règlement (CE) no 174/1999 de la Commission [3] prévoit qu’aucune restitution n'est octroyée lors d'une exportation de fromage dont le prix franco-frontière, avant l'application de la restitution dans l'État membre d'exportation, est inférieur à 230 EUR par 100 kilogrammes. Cette disposition ne s’applique pas au fromage relevant du code 0406 90 33 9919 de la nomenclature des restitutions. Dans ces circonstances et au vu de la demande élevée de certificats d’exportation, il convient d’appliquer cette disposition à tous les fromages sans exception.
(5) La note 10 du secteur 9 de l’annexe I du règlement (CEE) no 3846/87, applicable aux fromages râpés, en poudre et aux fromages fondus, établit que les matières non lactiques ajoutées ne seront pas prises en compte pour le calcul de la restitution. Il convient d’étendre cette disposition à tous les fromages et de mieux décrire les matières non lactiques concernées. Il peut ne pas être possible pour l’exportateur, voire plus difficile encore pour les autorités compétentes, de déterminer le poids de ces matières. Il convient donc de réduire la restitution d'un montant forfaitaire.
(6) La restitution est octroyée sur le poids net des fromages. Une certaine confusion peut exister lorsque les fromages sont entourés d’une enveloppe de paraffine, de cendre ou de cire ou qu’ils sont enveloppés dans un film plastique. Il convient de prévoir que ce type d'emballage ne fait pas partie du poids net du produit pour le calcul de la restitution. Il peut ne pas être possible pour l’exportateur et pour les autorités compétentes de déterminer le poids du film plastique, de la paraffine et de la cendre. Il convient donc de réduire la restitution d'un montant forfaitaire.
(7) Il y a lieu de modifier le règlement (CEE) no 3846/87 et le règlement (CE) no 174/1999 en conséquence.
(8) Les mesures prévues au présent règlement sont conformes à l'avis du comité de gestion du lait et des produits laitiers,
L’annexe I du règlement (CEE) no 3846/87 est modifiée conformément à l'annexe du présent règlement.
À l’article 3 du règlement (CE) no 174/1999, le quatrième paragraphe est supprimé.
Le présent règlement entre en vigueur le jour suivant celui de sa publication au Journal officiel de l'Union européenne.
Il est applicable aux certificats d'exportation demandés à partir du 27 mai 2005.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 559/2005 de la Commission
portant ouverture d'une enquête sur un éventuel contournement des mesures antidumping instituées par le règlement (CE) no 2074/2004 du Conseil sur les importations de certains mécanismes pour reliure à anneaux originaires de la République populaire de Chine par des importations de certains mécanismes pour reliure à anneaux expédiés de la République démocratique populaire Lao, qu'ils aient ou non été déclarés originaires de ce pays, et soumettant ces importations à enregistrement
LA COMMISSION DES COMMUNAUTÉS EUROPÉENNES,
vu le traité instituant la Communauté européenne,
vu le règlement (CE) no 384/96 du Conseil du 22 décembre 1995 relatif à la défense contre les importations qui font l'objet d'un dumping de la part de pays non membres de la Communauté européenne [1] (ci-après dénommé "règlement de base"), et notamment son article 13, paragraphe 3, et son article 14, paragraphes 3 et 5,
après consultation du comité consultatif,
(1) La Commission a été saisie d'une demande, conformément à l'article 13, paragraphe 3, du règlement de base, l'invitant à ouvrir une enquête sur un éventuel contournement des mesures antidumping instituées sur les importations de certains mécanismes pour reliure à anneaux originaires de la République populaire de Chine.
(2) La demande a été déposée le 28 février 2005 par Ring Alliance Ringbuchtechnik GmbH au nom de producteurs représentant plus de 70 % de la production communautaire de certains mécanismes pour reliure à anneaux.
(3) Les produits concernés par l'éventuel contournement sont certains mécanismes pour reliure à anneaux, normalement déclarés sous le code NC ex83051000 originaires de la République populaire de Chine. Ce dernier est donné à titre purement indicatif.
(4) Les produits incriminés sont certains mécanismes pour reliure à anneaux expédiés de la République démocratique populaire lao (ci-après dénommés "produits incriminés"), normalement déclarés sous le même code NC que les produits concernés originaires de la République populaire de Chine.
(5) Les mesures actuellement en vigueur et qui feraient l'objet d'un contournement sont les mesures antidumping instituées par le règlement (CE) no 2074/2004 du Conseil [2], étendu aux importations des mêmes produits expédiés du Viêt Nam [3].
(6) La demande contient des éléments de preuve suffisants pour attester à première vue que les mesures antidumping appliquées aux importations des produits concernés originaires de la République populaire de Chine sont contournées par le transbordement et/ou l'assemblage en République démocratique populaire lao des produits incriminés. Les éléments de preuve présentés sont les suivants:
- la demande montre d'importants changements dans la configuration des échanges, les importations des produits incriminés ayant sensiblement augmenté, tandis que celles des produits concernés originaires de la République populaire de Chine ont diminué à la suite de l'institution des mesures, sans qu'il existe de motivation ou de justification suffisante à ces changements autre que l'institution du droit,
- cette modification de la configuration des échanges semble résulter du transbordement et/ou de l'assemblage, en République démocratique populaire lao, de certains mécanismes pour reliure à anneaux originaires de la République populaire de Chine,
- en outre, la demande contient des éléments de preuve suffisants pour attester à première vue que les effets correctifs des mesures antidumping actuellement appliquées aux importations des produits concernés originaires de la République populaire de Chine sont compromis en termes de prix et de quantité. Des importations de produits incriminés en volumes importants semblent avoir remplacé des importations de produits concernés originaires de la République populaire de Chine,
- enfin, la demande contient des éléments de preuve suffisants pour attester à première vue que les prix des produits incriminés font l'objet de pratiques de dumping par rapport à la valeur normale précédemment établie pour certains mécanismes pour reliure à anneaux originaires de la République populaire de Chine,
- si des pratiques de contournement via la République démocratique populaire lao, autres que le transbordement et l'assemblage, couvertes par l'article 13 du règlement de base, venaient à être constatées au cours de la procédure, elles pourraient, elles aussi, être soumises à enquête.
(7) Compte tenu de ce qui précède, la Commission a conclu qu'il existait des éléments de preuve suffisants pour justifier l'ouverture d'une enquête, conformément à l'article 13 du règlement de base, et pour rendre obligatoire l'enregistrement des importations de certains mécanismes pour reliure à anneaux expédiés de la République démocratique populaire lao, qu'ils aient ou non été déclarés originaires de ce pays, conformément à l'article 14, paragraphe 5, du règlement de base.
(8) Afin d'obtenir les informations qu'elle juge nécessaires à son enquête, la Commission enverra des questionnaires aux producteurs-exportateurs et à leurs associations à la République démocratique populaire lao, aux producteurs-exportateurs et à leurs associations en République populaire de Chine, aux importateurs et à leurs associations dans la Communauté qui ont coopéré à l'enquête ayant abouti aux mesures existantes ou qui sont cités dans la demande, ainsi qu'aux autorités chinoises et laotiennes. Le cas échéant, des informations pourront également être demandées à l'industrie communautaire.
(9) En tout état de cause, toutes les parties intéressées doivent immédiatement prendre contact avec la Commission, avant la date fixée à l'article 3 du présent règlement, afin de savoir si elles sont citées dans la demande et, s'il y a lieu, de demander un questionnaire dans le délai précisé à l'article 3, paragraphe 1, étant donné que le délai fixé à l'article 3, paragraphe 2, s'applique à toutes les parties intéressées.
(10) Les autorités de la République populaire de Chine et de la République démocratique populaire lao seront informées de l'ouverture de l'enquête et recevront une copie de la demande.
(11) Toutes les parties intéressées sont invitées à faire connaître leur point de vue par écrit et à fournir des éléments de preuve à l'appui. En outre, la Commission entendra les parties intéressées, pour autant qu'elles en fassent la demande par écrit et prouvent qu'il existe des raisons particulières de les entendre.
c) Dispense d'enregistrement des importations ou des mesures
(12) Étant donné que l'éventuel contournement des mesures intervient en dehors de la Communauté, des dispenses peuvent être accordées, conformément à l'article 13, paragraphe 4, du règlement de base, aux producteurs des produits concernés à même de démontrer qu'ils ne sont pas liés à des producteurs soumis aux mesures et dont il a été constaté qu'ils ne s'adonnent pas aux pratiques de contournement définies à l'article 13, paragraphes 1 et 2, du règlement de base. Les producteurs souhaitant bénéficier d'une telle dispense doivent présenter une demande à cet effet, dûment étayée par des éléments de preuve, dans le délai fixé à l'article 3, paragraphe 3, du présent règlement.
(13) En vertu de l'article 14, paragraphe 5, du règlement de base, les importations des produits incriminés doivent être soumises à enregistrement, afin de faire en sorte que, dans l'hypothèse où l'enquête conclurait à l'existence d'un contournement, des droits antidumping d'un montant approprié puissent être perçus, avec effet rétroactif à compter de la date de l'enregistrement, sur lesdits produits importés, expédiés de la République démocratique populaire lao.
(14) Dans l'intérêt d'une bonne administration, il convient de fixer un délai pour permettre:
- aux parties intéressées de se faire connaître de la Commission, d'exposer leur point de vue par écrit, de transmettre leurs réponses au questionnaire ou de présenter toute autre information à prendre en considération lors de l'enquête;
- aux producteurs laotiens de demander une dispense d'enregistrement ou des mesures;
- aux parties intéressées de demander par écrit à être entendues par la Commission.
(15) Il est à noter que les parties ne peuvent exercer la plupart des droits procéduraux énoncés dans le règlement de base que si elles se sont fait connaître dans le délai mentionné à l'article 3 du présent règlement.
(16) Lorsqu'une partie intéressée refuse l'accès aux informations nécessaires ou ne les fournit pas dans les délais prévus ou fait obstacle de façon significative à l'enquête, des conclusions préliminaires ou finales, positives ou négatives, peuvent être établies sur la base des données disponibles, conformément à l'article 18 du règlement de base.
(17) S'il est constaté qu'une partie intéressée a fourni un renseignement faux ou trompeur, ce renseignement n'est pas pris en considération et il peut être fait usage des données disponibles, conformément à l'article 18 du règlement de base. Lorsqu'une partie intéressée ne coopère pas ou ne coopère que partiellement et que les conclusions sont établies sur la base des données disponibles, conformément à l'article 18 du règlement de base, il peut en résulter pour ladite partie une situation moins favorable que si elle avait coopéré,
Une enquête est ouverte, conformément à l'article 13, paragraphe 3, du règlement (CE) no 384/96, afin de déterminer si les importations, dans la Communauté, de certains mécanismes pour reliure à anneaux expédiés de la République démocratique populaire lao, qu'ils aient ou non été déclarés originaires de ce pays, relevant du code NC ex83051000 (codes TARIC 8305100013 et 8305100023), contournent les mesures instituées par le règlement (CE) no 2074/2004.
Aux fins du présent règlement, les mécanismes pour reliure à anneaux sont composés de deux plaques rectangulaires ou fils en acier, comprenant au moins 4 demi-anneaux en fil d'acier, le tout étant maintenu par une plaque de recouvrement en acier. Ils s'ouvrent en tirant sur les demi-anneaux ou à l'aide d'un petit dispositif en acier fixé sur le mécanisme.
Conformément à l'article 13, paragraphe 3, et à l'article 14, paragraphe 5, du règlement (CE) no 384/96, les autorités douanières sont invitées à prendre les mesures nécessaires pour enregistrer les importations dans la Communauté visées à l'article 1er du présent règlement.
L'enregistrement prend fin neuf mois après la date d'entrée en vigueur du présent règlement.
La Commission peut, par voie de règlement, enjoindre aux autorités douanières de cesser l'enregistrement des importations dans la Communauté des produits fabriqués par les producteurs dont il s'est avéré, à la suite d'une demande de dispense d'enregistrement, qu'ils n'ont pas contourné les droits antidumping.
1. Les questionnaires doivent être demandés à la Commission dans les quinze jours qui suivent la publication du présent règlement au Journal officiel de l'Union européenne.
2. Les parties intéressées peuvent se faire connaître de la Commission, présenter leur point de vue par écrit ainsi que les réponses au questionnaire ou toute autre information, qui, pour être pris en considération au cours de l'enquête, seront présentés, sauf indication contraire, dans les quarante jours à compter de la date de publication du présent règlement au Journal officiel de l'Union européenne.
3. Les producteurs laotiens sollicitant une dispense de l'enregistrement des importations ou des mesures doivent présenter une demande dûment étayée par des éléments de preuve dans le même délai de quarante jours.
4. Les parties intéressées peuvent également demander à être entendues par la Commission dans le même délai de quarante jours.
5. Toute information concernant l'affaire et toute demande d'audition, de questionnaire et de dispense doivent être présentées par écrit (autrement que sous format électronique, sauf indication contraire) et mentionner le nom, l'adresse, l'adresse de courrier électronique, les numéros de téléphone, de télécopieur et/ou de télex de la partie intéressée. Tous les commentaires écrits, y compris les informations demandées dans le présent règlement, les réponses au questionnaire et la correspondance des parties intéressées, fournis à titre confidentiel, porteront la mention "restreint" [4] et seront accompagnés, conformément à l'article 19, paragraphe 2, du règlement de base, d'une version non confidentielle portant la mention "version destinée à être consultée par les parties concernées"; ils devront être envoyés à l'adresse suivante:
Télécopieur (32-2) 295 65 05.
Le présent règlement entre en vigueur le jour suivant celui de sa publication au Journal officiel de l'Union européenne.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 560/2005 du Conseil
infligeant certaines mesures restrictives spécifiques à l'encontre de certaines personnes et entités au regard de la situation en Côte d'Ivoire
LE CONSEIL DE L'UNION EUROPÉENNE,
vu le traité instituant la Communauté européenne, et notamment ses articles 60, 301 et 308,
vu la position commune 2004/852/PESC du Conseil du 13 décembre 2004 concernant des mesures restrictives à l'encontre de la Côte d'Ivoire [1],
vu la proposition de la Commission,
vu l'avis du Parlement européen [2],
(1) Aux termes de sa résolution no 1572 (2004) du 15 novembre 2004, le Conseil de sécurité des Nations unies, statuant au titre du chapitre VII de la charte des Nations unies et déplorant la reprise des hostilités en Côte d'Ivoire ainsi que les violations répétées de l'accord de cessez-le-feu du 3 mai 2003, a décidé d'imposer certaines mesures restrictives à l'encontre de la Côte d'Ivoire.
(2) La position commune 2004/852/PESC prévoit la mise en œuvre des mesures arrêtées par la résolution no 1572 (2004) du Conseil de sécurité des Nations unies, notamment le gel des fonds et des ressources économiques des personnes désignées par le comité des sanctions des Nations unies compétent, qui font peser une menace sur le processus de paix et de réconciliation nationale en Côte d'Ivoire, notamment celles qui entravent l'application des accords de Linas-Marcoussis et d'Accra III, de toute autre personne qui serait reconnue responsable de violations graves des droits de l'homme et du droit humanitaire international en Côte d'Ivoire sur la base d'informations en la matière, de toute autre personne qui incite publiquement à la haine et à la violence, ainsi que de toute autre personne dont le comité aurait établi qu'elle agit en violation de l'embargo sur les armes également imposé par la résolution no 1572 (2004).
(3) Ces mesures entrent dans le champ d'application du traité et, pour éviter toute distorsion de concurrence, un acte communautaire est donc nécessaire pour en assurer la mise en œuvre en ce qui concerne la Communauté. Aux fins du présent règlement, le territoire de la Communauté est réputé englober les territoires des États membres auxquels le traité s'applique, dans les conditions prévues par celui-ci.
(4) Pour garantir que les mesures prévues dans le présent règlement soient efficaces, ce dernier devrait entrer en vigueur le jour de sa publication,
Aux fins du présent règlement, on entend par:
1) "comité des sanctions": le comité du Conseil de sécurité des Nations unies créé en application du paragraphe 14 de la résolution no 1572 (2004) du Conseil de sécurité des Nations unies;
2) "fonds": les actifs financiers et les avantages économiques de toute nature, et notamment, mais pas uniquement:
a) le numéraire, les chèques, les créances en numéraire, les traites, les ordres de paiement et autres instruments de paiement;
b) les dépôts auprès d'institutions financières ou d'autres entités, les soldes en comptes, les créances et les titres de créances;
c) les titres de propriété et d'emprunt, tels que les actions, les certificats représentatifs de valeurs mobilières, les obligations, les billets à ordre, les warrants, les obligations non garanties et les contrats sur produits dérivés, qu'ils soient négociés en bourse ou fassent l'objet d'un placement privé;
d) les intérêts, les dividendes ou autres revenus d'actifs ou plus-values perçus sur des actifs;
e) le crédit, le droit à compensation, les garanties, les garanties de bonne exécution ou autres engagements financiers;
f) les lettres de crédit, les connaissements, les contrats de vente;
g) tout document attestant la détention de parts d'un fonds ou de ressources financières;
h) tout autre instrument de financement à l'exportation;
3) "gel des fonds": toute action visant à empêcher tout mouvement, transfert, modification, utilisation ou manipulation de fonds qui aurait pour conséquence un changement de leur volume, de leur montant, de leur localisation, de leur propriété, de leur possession, de leur nature, de leur destination ou toute autre modification qui pourrait en permettre l'utilisation, notamment la gestion de portefeuille;
4) "ressources économiques": les avoirs de toute nature, corporels ou incorporels, mobiliers ou immobiliers, qui ne sont pas des fonds mais peuvent être utilisés pour obtenir des fonds, des biens ou des services;
5) "gel des ressources économiques": toute action visant à empêcher leur utilisation afin d'obtenir des fonds, des biens ou des services de quelque manière que ce soit, et notamment mais pas uniquement, leur vente, leur location ou leur mise sous hypothèque.
1. Tous les fonds et ressources économiques qui sont en la possession ou sous le contrôle direct ou indirect des personnes physiques ou morales ou entités énumérées à l'annexe I sont gelés.
2. Aucun fonds ou ressource économique n'est mis directement ou indirectement à la disposition des personnes physiques ou morales ou entités énumérées à l'annexe I ou utilisé à leur profit.
3. La participation volontaire et délibérée à des activités ayant pour objet ou pour effet direct ou indirect de tourner les mesures visées aux paragraphes 1 et 2 est interdite.
1. Par dérogation à l'article 2 et pour autant que les autorités compétentes des États membres énumérées à l'annexe II aient notifié au comité des sanctions leur intention d'autoriser l'accès à ces fonds et ressources économiques et que ce dernier ne leur ait pas signifié son refus dans les deux jours ouvrables suivant la notification, elles peuvent autoriser le déblocage ou la mise à disposition de fonds ou ressources économiques gelés, aux conditions qu'elles jugent appropriées, après avoir établi que ces fonds ou ressources économiques sont:
a) nécessaires pour régler des dépenses ordinaires, notamment pour payer des vivres, des loyers ou les mensualités de prêts hypothécaires, des médicaments ou des frais médicaux, des impôts, des primes d'assurance et pour assurer la rémunération de services d'utilité publique;
b) destinés exclusivement au règlement d'honoraires d'un montant raisonnable et au remboursement de dépenses engagées pour s'assurer les services de juristes;
c) destinés exclusivement au paiement de commissions ou de frais se rapportant à la gestion courante des fonds ou ressources économiques gelés.
2. Par dérogation à l'article 2, les autorités compétentes des États membres énumérées à l'annexe II peuvent autoriser le déblocage ou la mise à disposition de certains fonds ou ressources économiques gelés après avoir établi que ces fonds ou ressources économiques sont nécessaires pour couvrir des dépenses extraordinaires et à condition d'avoir notifié leur décision au comité des sanctions et que cette décision ait été approuvée par ledit comité, dans les conditions prévues au paragraphe 14 e) de la résolution no 1572 (2004) du Conseil de sécurité des Nations unies.
Par dérogation à l'article 2, les autorités compétentes des États membres énumérées à l'annexe II peuvent autoriser le déblocage de certains fonds et ressources économiques gelés, pour autant que les conditions suivantes soient réunies:
a) les fonds ou ressources économiques font l'objet d'une mesure judiciaire, administrative ou arbitrale prise avant le 15 novembre 2004 ou d'une décision judiciaire, administrative ou arbitrale rendue avant cette date;
b) les fonds ou ressources économiques sont exclusivement utilisés pour faire droit aux demandes garanties par une telle mesure ou dont la validité a été établie par une telle décision, dans les limites fixées par les lois et règlements régissant les droits des personnes admises à présenter de telles demandes;
c) la mesure ou la décision n'est pas rendue au bénéfice d'une personne ou d'une entité énumérée à l'annexe I;
d) la reconnaissance de la mesure ou de la décision n'est pas contraire à la politique menée dans l'État membre concerné;
e) les autorités compétentes ont notifié la mesure ou la décision au comité des sanctions.
L'autorité compétente concernée informe les autorités compétentes des autres États membres et la Commission de toute autorisation accordée en application des articles 3 ou 4.
L'article 2, paragraphe 2, ne s'applique pas aux majorations de comptes gelés effectuées sous la forme:
a) d'intérêts ou autres rémunérations de ces comptes, ou
b) de paiements dus en vertu de contrats, accords ou obligations qui ont été conclus ou contractés avant la date à laquelle ces comptes ont été soumis aux dispositions du présent règlement,
sous réserve que ces intérêts, autres rémunérations ou paiements sont gelés, conformément aux dispositions de l'article 2, paragraphe 1.
L'article 2, paragraphe 2, ne fait pas obstacle à ce que des crédits soient portés sur des comptes gelés par des institutions financières recevant des fonds transférés par des tierces parties et destinés au compte de personnes ou entités figurant sur la liste, pour autant que les majorations éventuelles de ces comptes soient également gelées. L'établissement financier informe sans retard les autorités compétentes de telles transactions.
1. Sans préjudice des règles applicables en matière de communication d'informations, de confidentialité et de secret professionnel, ainsi que des dispositions de l'article 284 du traité, les personnes physiques et morales, les entités et les organismes:
a) fournissent immédiatement toute information susceptible de favoriser le respect du présent règlement, concernant notamment les comptes et montants gelés en vertu de l'article 2, aux autorités compétentes des États membres énumérées dans l'annexe II, dans lesquels ils résident ou sont établis, et transmettent cette information à la Commission, directement ou par l'intermédiaire de ces autorités;
b) coopèrent avec les autorités compétentes énumérées à l'annexe II dans le cadre de la vérification de cette information.
2. Toute information supplémentaire reçue directement par la Commission est communiquée aux autorités compétentes de l'État membre concerné.
3. Toute information fournie ou reçue conformément au présent article est utilisée aux seules fins pour lesquelles elle a été fournie ou reçue.
Le gel des fonds et ressources économiques ou le refus d'en autoriser la disposition, exécutés de bonne foi au motif qu'une telle action est conforme aux dispositions du présent règlement, n'entraînent, pour la personne morale ou physique ou l'entité qui y procède, sa direction ou ses employés, aucune responsabilité de quelque nature que ce soit, à moins qu'il soit établi qu'il y a eu négligence dans le cadre du gel de ces fonds et ressources.
La Commission et les États membres s'informent sans délai des mesures prises en application du présent règlement et se communiquent les informations utiles dont ils disposent en relation avec le présent règlement, et notamment celles concernant les violations du présent règlement, les problèmes rencontrés dans sa mise en œuvre et les jugements rendus par les juridictions nationales.
La Commission est habilitée à:
a) modifier l'annexe I sur la base de décisions du comité des sanctions, et
b) modifier l'annexe II sur la base des informations fournies par les États membres.
Les États membres arrêtent le régime des sanctions à appliquer en cas d'infraction aux dispositions du présent règlement et prennent toutes les mesures nécessaires pour garantir leur mise en œuvre. Ces sanctions doivent être effectives, proportionnées et dissuasives. Les États membres notifient ce régime à la Commission, sans délai, après l'entrée en vigueur du présent règlement et l'informent aussi de toute modification ultérieure.
a) au territoire de la Communauté, y compris son espace aérien;
b) à bord de tout aéronef ou de tout navire relevant de la juridiction d'un État membre;
c) à toute personne, à l'intérieur ou à l'extérieur du territoire de la Communauté, qui est ressortissante d'un État membre;
d) à toute personne morale, à tout groupe ou à toute entité, établis ou constitués selon le droit d'un État membre;
e) à toute personne morale, à tout groupe ou à toute entité exerçant une activité économique dans la Communauté.
Le présent règlement entre en vigueur le jour de sa publication au Journal officiel de l'Union européenne.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
Règlement (CE) no 561/2005 de la Commission
établissant les valeurs forfaitaires à l'importation pour la détermination du prix d'entrée de certains fruits et légumes
LA COMMISSION DES COMMUNAUTÉS EUROPÉENNES,
vu le traité instituant la Communauté européenne,
vu le règlement (CE) no 3223/94 de la Commission du 21 décembre 1994 portant modalités d'application du régime à l'importation des fruits et légumes [1], et notamment son article 4, paragraphe 1,
(1) Le règlement (CE) no 3223/94 prévoit, en application des résultats des négociations commerciales multilatérales du cycle d'Uruguay, les critères pour la fixation par la Commission des valeurs forfaitaires à l'importation des pays tiers, pour les produits et les périodes qu'il précise dans son annexe.
(2) En application des critères susvisés, les valeurs forfaitaires à l'importation doivent être fixées aux niveaux repris à l'annexe du présent règlement,
Les valeurs forfaitaires à l'importation visées à l'article 4 du règlement (CE) no 3223/94 sont fixées comme indiqué dans le tableau figurant en annexe.
Le présent règlement entre en vigueur le 14 avril 2005.
Le présent règlement est obligatoire dans tous ses éléments et directement applicable dans tout État membre.
